language: python
sudo: false
python:
  - "2.7"
  - "3.4"
before_install:
  - sudo apt-get update
install:
  - pip install flake8
before_script:
  - "flake8 --show-source --builtins=_ nest"
script:
  - pip install .
  - python setup.py sdist
deploy:
  - provider: pypi
    user: $pypi_test_user
    password: $pypi_test_pass
    server: $pypi_test
    on:
      branch: deploy-test
      python: "3.4"
  - provider: pypi
    user: $pypi_user
    password: $pypi_pass
    server: $pypi
    on:
      branch: deploy
      python: "3.4"
